/* eslint-disable react/no-unescaped-entities */
import Content from "@/components/Content";
import Header from "@/components/Header";
import TableAndModal from "@/components/Table";
import { Box, useMediaQuery } from "@mui/material";
import Head from "next/head";

export default function Home() {
  const desktop = useMediaQuery("(min-width:900px)");
  return (
    <Box>
      <Head>
        <title>Rick And Morty Wiki</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/portal.svg" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Domine&family=Heebo&family=Kalnia&family=Poppins:wght@400;600;700&display=swap');
        </style>
      </Head>
      <main>
        <Header />
        <Box
          sx={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            height: "100vh",
          }}
        >
          {desktop ? <Content /> : <TableAndModal />}
        </Box>
      </main>
    </Box>
  );
}
