import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Box, useMediaQuery } from "@mui/material";
import Header from "@/components/Header";
import Content from "@/components/Content";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const smartphone = useMediaQuery("(min-width:600px)");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Box
          sx={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            height: "100vh",
            bgcolor: "black",
            flexDirection: "column",
          }}
        >
          <div className="imageContainer">
            <Image
              className="teste"
              src={"/portal.svg"}
              width={300}
              height={300}
              alt={"portal"}
            ></Image>
          </div>
          {smartphone ? <Content /> : <>asads </>}
        </Box>
      </main>
    </>
  );
}
